# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Removal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remove_order_id', models.CharField(max_length=120)),
                ('product_id', models.CharField(max_length=120)),
                ('fn_sku', models.CharField(max_length=120)),
                ('s_num', models.CharField(max_length=120)),
                ('sku', models.CharField(max_length=120)),
                ('product', models.CharField(max_length=120)),
                ('qty', models.CharField(max_length=120)),
                ('asin', models.CharField(max_length=120)),
                ('notes', models.TextField()),
                ('condition_id', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
