# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('removal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='removal',
            name='condition_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='removal',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='removal',
            name='qty',
            field=models.IntegerField(),
        ),
    ]
