# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('removal', '0002_auto_20171003_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='removal',
            old_name='product_id',
            new_name='finale_id',
        ),
        migrations.RenameField(
            model_name='removal',
            old_name='s_num',
            new_name='ser_tag',
        ),
        migrations.AlterField(
            model_name='removal',
            name='product',
            field=models.CharField(max_length=220),
        ),
    ]
